"""Add elo_rating to players table

Revision ID: 1d2d2fb2c0d5
Revises: 2b730cac095e
Create Date: 2025-11-10 14:22:56.575889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2d2fb2c0d5'
down_revision: Union[str, Sequence[str], None] = '2b730cac095e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('elo_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'elo_rating')
    # ### end Alembic commands ###
