"""Add match score fields: player1_games, player2_games, games_score

Revision ID: f4d825fe9491
Revises: 1d2d2fb2c0d5
Create Date: 2025-11-10 19:07:19.649284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d825fe9491'
down_revision: Union[str, Sequence[str], None] = '1d2d2fb2c0d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Add match score fields."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite migration: Add columns if they don't exist
    # Note: SQLite doesn't support IF NOT EXISTS for ALTER TABLE
    # The columns are already in the schema via the model definition
    # This migration is a no-op since columns were added via direct model updates
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - Remove match score fields."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op downgrade since this is recording existing model columns
    pass
    # ### end Alembic commands ###
